version: '3.4'

services:
  pushnotifications-postgres:
    container_name: pushnotificationsdemo-postgres
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pushnotifications-db
    command: ['postgres', '-c', 'log_statement=all']

volumes:
  postgresdata:
